# Usage: ansible-playbook test_greenmaker.yml -l <target_host> -i <inventory_file> -e '{ "target_scenarios":["sample_wait"] }'
---
# "metadata" provides descriptive information about the scenario, such as its purpose and the actions that it takes
metadata:
  id: "100001"
  version: "1.0.0"
  name: "sample_wait"
  description: |
    This scenario demonstrates usage of the "wait" action this scenario starts with the execute an "echo" action to print a statement regarding the length of wait time. 
    The  wait action is then invoked, passing a value of 20 seconds for the duration argument.  Finally, an "echo" action is executed to print that the wait has completed.
    Note: This scenario executes in "test mode"  the "wait" action has logic built-in to override the passed in duration value to only wait one second.
  product_family:
    - "All"
  severity: "3"
  device_roles:
    - "TBD"
  categories: []
  related_defects: []
  date_modified: ""
  alert_created: false
  troubleshooting_actions: ""

# "triggers" describes the network event(s) or trigger conditions upon which the scenario workflow will be executed.
# This sample scenario will be manually triggered, so we leave the triggers list empty.
triggers: []

# "workflow" provides a list of steps that will be executed by the auto-remediation workflow engine (e.g. Greenmaker role in Ansible)
workflow:
  - step:
      metadata:
        name: "wait"
        description: |
          Echo "Executing Wait action", to the Ansible execution logs
      on_true:
        - echo: 
            args:
              message: |
                Waiting for 1 second
        - wait:
            args:
              duration: 1
        - echo: 
            args:
              message: |
                Wait complete, execution completed
        - exit:
            args:
              reason: Execution complete.


# "tests" describes available tests that can be executed for this scenario in Test Mode and any relevant simulated data for the test  
tests: 
  validation:
    - metadata:
        name: default_test
        description: | 
          Test execution of wait action
      extra_vars:
        - alert_vars: {}
      input: {}

library: {}
