---
- name: Initialize action_log for capturing debug data for action in a JSON format
  set_fact:
    action_log: {}
    action_name: "{{ (action.keys() | list)[0] }}"

- debug:
    msg: "Executing {{ action_name }} action"
    verbosity: 1

- debug:
    msg: "Failure REASON: {{ action['fail']['args']['reason'] }}"
    verbosity: 1

- name: log fail reason to cli log file
  lineinfile:
    line: "! ACTION: fail\n! REASON: {{ action['fail']['args']['reason'] }}"
    insertafter: EOF
    dest: "{{ gm_log_path }}/{{ gm_log_cli_name }}"
  check_mode: no
  delegate_to: localhost

- name: add custom fields
  set_fact:
    custom_fields: "{{ action['fail']['custom_fields'] | default({})}}" 

- name: Generate workflow_log_action for current action
  set_fact:
    workflow_log_action: "{{ { action_name: ( action[action_name] | combine( { 'action_log': action_log | default({}) } ) ) } }}"

- name: Append workflow_log_action_list with workflow_log_action for current action
  set_fact:
    workflow_log_action_list: "{{ workflow_log_action_list + [ workflow_log_action ] }}"

- name: Append workflow_log_action_list to workflow_log_step
  set_fact:
    workflow_log_step: "{{ workflow_log_step | combine( { remediation_selection: workflow_log_action_list } ) }}"

- name: Append workflow_log_step to workflow_log
  set_fact:
    workflow_log: "{{ workflow_log + [ { 'step': workflow_log_step } ] }}"

- name: Invoke workflow failure
  fail:
    msg:  "Manual failure Action triggered REASON: {{ action['fail']['args']['reason'] }}"

