---
- debug:
    msg: "Executing {{ (action.keys() | list)[0] }} for {{ ansible_network_os }}"
    verbosity: 1

- name: Initialize vars
  set_fact:
    cli_logs: {}

- name: Execute commands for NX-OS device
  block:

  - name: Execute commands for NX-OS device
    nxos_command: 
      commands: "{{ action['exec_cli']['args']['commands'] }}"
    vars:
      ansible_command_timeout: "{{ action['exec_cli']['args']['timeout'] | default(60) | int }}"
    register: cli_exec_data_raw

  - name: Append cli logs to same file
    lineinfile:
      dest: "{{ gm_log_path }}/{{ gm_log_cli_name }}"
      line: | 
          >> {{ action['exec_cli']['args']['commands'][index] }}
          {{ current_std_output }}
      insertafter: EOF
    check_mode: no
    loop: "{{ cli_exec_data_raw['stdout'] }}"
    loop_control:
        loop_var: current_std_output
        index_var: index
    delegate_to: localhost
    
  - set_fact:
      cli_logs: "{{ dict( action['exec_cli']['args']['commands'] | zip( cli_exec_data_raw['stdout'] ) ) }}"

  when: test_mode == false or (test_mode == true and test_type == 'remediation')
  
- name: When in Validation Test Mode mode, generate debug output and log non-execution of commands to file
  block:

  - name: Validation Test Mode mode debug output
    debug:
      msg: |
        The following commands were not executed due to use of Validation Test Mode:
        {{ action['exec_cli']['args']['commands'] }}
      verbosity: 1

  - name: Append cli logs to same file
    lineinfile:
      dest: "{{ gm_log_path }}/{{ gm_log_cli_name }}"
      line: | 
          >> {{ command }}
          Execution skipped due to Validation Test Mode
      insertafter: EOF
    check_mode: no
    loop: "{{ action['exec_cli']['args']['commands'] }}"
    loop_control:
        loop_var: command
        index_var: index
    delegate_to: localhost

  when: test_mode == true and test_type == 'validation'

- name: Capture action logs for JSON workflow logs
  set_fact:
    action_log: "{{ action_log | combine({ 'cli_logs': cli_logs | default({}) }) }}"
