---
- debug:
    msg: "Executing {{ (action.keys() | list)[0] }}"
    verbosity: 1

- name: Log action to CLI log file
  lineinfile:
    dest: "{{ gm_log_path }}/{{ gm_log_cli_name }}"
    line: "! ACTION: {{ (action.keys() | list)[0] }}\n"
    insertafter: EOF
  check_mode: no
  delegate_to: localhost

- set_fact:
    call_label: "{{ action['call']['args']['label'] }}"

- set_fact:
    actions: "{{ scenario['library'][call_label]}}"

- name: Execute actions
  include_tasks:
    file: actions.yml
  when: actions
